Update configure to reject --prefix with a relative path argument
configure checks that the path passed to --prefix starts with a '/'.
Also, if the `pathchk` utility exists, it is used to check that the path
is usable.

diff --git a/release/configure b/release/configure
--- a/release/configure
+++ b/release/configure
@@ -3,7 +3,7 @@
 # Giraffe Library configure script
 # This script generates config.mk that is included by Makefile.
 #
-# Copyright (C) 2015, 2020-2021 Phil Clayton <phil.clayton@veonix.com>
+# Copyright (C) 2015, 2020-2021, 2024 Phil Clayton <phil.clayton@veonix.com>
 #
 # This file is part of the Giraffe Library runtime.  For your rights to use
 # this file, see the file 'LICENCE.RUNTIME' distributed with Giraffe Library
@@ -214,6 +214,46 @@ EOF
   exit $SHOWHELP
 fi
 
+# Check for required utilities
+
+if ! command -v which > /dev/null
+then
+  echo
+  echo "error: 'which' command not found"
+  exit 1
+fi
+
+pathchk=$(command which pathchk 2> /dev/null)
+if [ -z "${pathchk}" ]
+then
+  pathchk=":"
+fi
+
+pkgconfig=$(command which pkg-config 2> /dev/null)
+if [ -z "${pkgconfig}" ]
+then
+  echo
+  echo "error: 'pkg-config' command not found"
+  exit 1
+fi
+
+# Check that PREFIX is absolute and contains a usable path.
+case "${PREFIX}" in
+(/*)
+  if ! pathchk "${PREFIX}"
+  then
+    echo
+    echo "error: installation directory \"${PREFIX}\" is not a usable path"
+    exit 1
+  fi
+  ;;
+(*)
+  echo
+  echo "error: installation directory \"${PREFIX}\" is not absolute (does not start with a '/')"
+  exit 1
+  ;;
+esac
+
 # Check that PREFIX does not contain whitespace because such a path does not
 # appear to work as a value for the MLton option '-mlb-path-var name value'.
 if echo "${PREFIX}" | grep "[[:space:]]" > /dev/null
@@ -222,14 +262,6 @@ then
   echo "error: installation directory \"${PREFIX}\" contains whitespace"
   echo
   echo "The installation directory must not contain whitespace because such a path does not work as a value for the MLton option '-mlb-path-var name value'"
-  exit 1
-fi
-
-# Check that pkg-config is present
-if ! which pkg-config > /dev/null 2>&1
-then
-  echo
-  echo "error: pkg-config command not found"
   exit 1
 fi
 
@@ -419,15 +451,15 @@ then
     echo "  lib directory:     ${POLYML_LIBDIR}"
 
   # check with pkg-config
-  elif pkg-config --exists polyml
+  elif "${pkgconfig}" --exists polyml
   then
-    POLYML_VERSION_EXPECTED=$(pkg-config --modversion polyml)
+    POLYML_VERSION_EXPECTED=$("${pkgconfig}" --modversion polyml)
     echo "found version ${POLYML_VERSION_EXPECTED} using pkg-config"
 
     HAVE_POLYML="1"
-    POLYML_BINDIR=$(pkg-config --variable=bindir polyml)
-    POLYML_LIBDIR=$(pkg-config --variable=libdir polyml)
-    POLYML_INCLUDEDIR=$(pkg-config --variable=includedir polyml)  # not used
+    POLYML_BINDIR=$("${pkgconfig}" --variable=bindir polyml)
+    POLYML_LIBDIR=$("${pkgconfig}" --variable=libdir polyml)
+    POLYML_INCLUDEDIR=$("${pkgconfig}" --variable=includedir polyml)  # not used
 
     echo "  bin directory:     ${POLYML_BINDIR}"
     echo "  lib directory:     ${POLYML_LIBDIR}"
@@ -573,16 +605,16 @@ do
   then
     printf "Checking %s... " "${NAME}"
 
-    if pkg-config --exists "${PKGNAME}"
+    if "${pkgconfig}" --exists "${PKGNAME}"
     then
-      MODVERSION=$(pkg-config --modversion "${PKGNAME}")
+      MODVERSION=$("${pkgconfig}" --modversion "${PKGNAME}")
       echo "found version ${MODVERSION}"
 
       USE_LIB=
       if [ -n "${VERSION}" ]
       then
         # check installed version is new enough
-        if pkg-config --atleast-version="${VERSION}" "${PKGNAME}"
+        if "${pkgconfig}" --atleast-version="${VERSION}" "${PKGNAME}"
         then
           REL=">="
         else
